name: Build and Deploy
on:
  # run on changes to files in src/ or public/ in the main branch
  push:
    paths:
      - 'src/**'
      - 'public/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21.5.0'
    - run: npm install
    - run: npm run build
    - run: echo "debates2024.info" > dist/CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_dir: ./dist

